name: "Auto compile IPK with OpenWrt SDK"

permissions:
  contents: write
  packages: write
  
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: "SSH connection to Actions"
        required: false
        default: "false"
  push:
    branches:
      - "main"
    paths:
      - "luci-app-3ginfo-lite/Makefile"

env:
  TZ: Asia/Jakarta

jobs:
  job_check:
    if: github.repository == ${{ github.repository }}
    name: Check Version
    runs-on: ubuntu-latest
    outputs:
      ginfo_version: ${{ steps.check_version.outputs.latest_version }}
      has_update: ${{ steps.check_version.outputs.has_update }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: "main"

      - name: Check version
        id: check_version
        env:
          url_release: https://api.github.com/repos/${{ github.repository }}/releases/latest
        run: |
          latest_version=$(grep -oP 'PKG_VERSION:=\K.*' luci-app-3ginfo-lite/Makefile | sed 's/^/v/')
          latest_release=$(wget -qO- -t1 -T2 ${{ env.url_release }} | awk -F '"' '/tag_name/{print $4}')
          has_update=$([ "${latest_version}" != "${latest_release}" ] && echo true || echo false)

          echo "latest_version=${latest_version}" >> $GITHUB_OUTPUT
          echo "has_update=${has_update}" >> $GITHUB_OUTPUT

          echo "latest_version: ${latest_version}"
          echo "latest_release: ${latest_release}"
          echo "has_update: ${has_update}"

      - name: Generate new tag & release
        if: steps.check_version.outputs.has_update == 'true'
        uses: softprops/action-gh-release@v2 # Diperbarui ke v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ steps.check_version.outputs.latest_version }}
          tag_name: ${{ steps.check_version.outputs.latest_version }}
          # Rilis ini awalnya dibuat kosong, file akan ditambahkan oleh job_build
          files: | 
          body: "Rilis otomatis untuk ${{ steps.check_version.outputs.latest_version }}"

  job_build_3ginfo:
    name: Build luci-app-3ginfo-lite (main)
    needs: job_check
    if: needs.job_check.outputs.has_update == 'true'
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Checkout kode repositori Anda
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          echo "Install required build dependencies..."
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install -y zstd build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext \
            git libncurses5-dev libssl-dev python3-venv rsync unzip zlib1g-dev file wget
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean

      - name: Cache OpenWrt SDK
        id: cache-sdk
        uses: actions/cache@v4
        with:
          path: sdk
          key: openwrt-sdk-x86-64-v24.10.0 # Ganti ini jika versi SDK berubah

      - name: Initialize SDK environment
        if: steps.cache-sdk.outputs.cache-hit != 'true'
        env:
          url_sdk: https://archive.openwrt.org/releases/24.10.0/targets/x86/64/openwrt-sdk-24.10.0-x86-64_gcc-13.3.0_musl.Linux-x86_64.tar.zst
        run: |
          wget ${{ env.url_sdk }}
          file_name=$(basename "${{ env.url_sdk }}")
          mkdir sdk && tar --zstd -xvf $file_name -C ./sdk --strip-components=1
          cd sdk
          echo "src-git base https://github.com/openwrt/openwrt.git;main" > feeds.conf
          echo "src-git-full packages https://github.com/openwrt/packages.git;master" >> feeds.conf
          echo "src-git-full luci https://github.com/openwrt/luci.git;master" >> feeds.conf
          echo "src-git-full routing https://git.openwrt.org/feed/routing.git;master" >> feeds.conf
          # Hapus 'git clone' dari sini
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig

      - name: Configure luci-app-3ginfo-lite
        run: |
          cd sdk
          # Buat symlink ke kode Anda yang sudah di-checkout
          ln -s $PWD/../luci-app-3ginfo-lite package/luci-app-3ginfo-lite
          
          # Hapus 'feeds install' untuk paket ini karena sudah dilink secara lokal
          # ./scripts/feeds install luci-app-3ginfo-lite
          
          echo "CONFIG_ALL_NONSHARED=n" > .config
          echo "CONFIG_ALL_KMODS=n" >> .config
          echo "CONFIG_ALL=n" >> .config
          echo "CONFIG_AUTOREMOVE=n" >> .config
          echo "CONFIG_LUCI_LANG_zh_Hans=y" >> .config
          echo "CONFIG_PACKAGE_luci-app-3ginfo-lite=m" >> .config
          make defconfig

      - name: Compile luci-app-3ginfo-lite
        id: compile
        run: |
          cd sdk
          echo "make package/luci-app-3ginfo-lite/{clean,compile} -j$(nproc)"
          make package/luci-app-3ginfo-lite/{clean,compile} -j$(nproc)
          
          # Buat direktori artifacts dan pindahkan IPK ke sana
          mkdir -p $PWD/../artifacts
          find bin/packages/ -type f -name "luci-app-3ginfo-lite*.ipk" -exec mv {} $PWD/../artifacts/ \;
          
          cd ..
          echo "status=success" >> $GITHUB_OUTPUT
          # Set variabel environment ke path artifacts
          echo "IPK_PATH=$PWD/artifacts" >> $GITHUB_ENV

      - name: Upload luci-app-3ginfo-lite IPKs to release
        uses: softprops/action-gh-release@v2 # Diperbarui ke v2
        if: steps.compile.outputs.status == 'success'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.job_check.outputs.ginfo_version }}
          # Arahkan ke file di dalam direktori artifacts
          files: ${{ env.IPK_PATH }}/*.ipk
